version: "2"
services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: "gotest_test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  # the main image, this is the application
  test:
    build:
      context: ./
      dockerfile: ./deployments/Dockerfile.dev
    image: "gotest:dev"
    environment:
      MIX_ENV: "test"
    command: "mix test"
    working_dir: /gotest
    volumes:
      - ./:/gotest
    links:
      - postgres

  build:
    build:
      context: ./
      dockerfile: ./deployments/Dockerfile.dev
    image: "gotest:dev"
    environment:
      MIX_ENV: "prod"
    command: sh -c "mix deps.get; mix phx.digest; mix release"
    working_dir: /gotest
    volumes:
      - ./:/gotest

  release:
    build:
      context: ./
      dockerfile: ./deployments/Dockerfile
      args:
        VERSION: "0.0.1"
        PORT: 4000
    image: "gotest:0.0.1"
    environment:
      MIX_ENV: "prod"